Repository MarczalTSIGP/SGTCC, pull requests merged in 2023-11, with the labels that each got.

#269 Feat/populate to generate all types of orientations
  app/services/populate/examination_boards.rb
  app/services/populate/orientations.rb
  app/services/populate/pdfs/monografia.pdf
  app/services/populate/pdfs/projeto.pdf
  app/services/populate/pdfs/proposta.pdf
  lib/tasks/db/populate.rake
Labels: chore

#260 Feat/display examination board notes for all included
  app/models/examination_board.rb
  app/models/examination_board_note.rb
  app/models/logics/examination_board/evaluators_responses.rb
  app/views/academics/examination_boards/_appointment_files.html.erb
  app/views/academics/examination_boards/_evaluated_status.html.erb
  app/views/academics/examination_boards/show.html.erb
  app/views/shared/examination_boards/_academic_activity.html.erb
  app/views/shared/examination_boards/_appointment_text_modal.html.erb
  app/views/shared/examination_boards/_evaluated_status.html.erb
  app/views/shared/examination_boards/_show.html.erb
  config/locales/pt-BR.yml
  run
  spec/factories/examination_board_notes.rb
  spec/features/academics/examination_boards/examination_boards_show_spec.rb
  spec/features/external_members/examination_board_notes/examination_board_notes_show_spec.rb
  spec/features/external_members/examination_boards/examination_boards_show_spec.rb
  spec/features/professors/examination_boards/examination_boards_show_spec.rb
  spec/features/responsible/examination_boards/examination_boards_show_spec.rb
  spec/features/tcc_one_professors/examination_boards/examination_boards_show_spec.rb
  spec/models/examination_board_spec.rb
Labels: feature

#256 Fix/error when external member tries to access examination details in certain conditions
  app/controllers/external_members/examination_boards_controller.rb
Labels: bug

#263 Padronização de impressão em A4
  app/assets/config/manifest.js
  app/assets/stylesheets/print.css
  app/javascript/components/signatures/documents/partials/term-header.vue
  app/javascript/packs/application.js
  app/views/layouts/academics/application.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/external_members/application.html.erb
  app/views/layouts/professors/application.html.erb
Labels: bug
